server:
  port: 8888
  servlet:
    context-path: /ac
spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  application:
    name: ac-server
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8000/eureka/
  instance:
    ip-address: true
